### 회원 가입(POST)
POST http://localhost:3001/auth
Content-Type: application/json

{
    "id": "test_id3",
    "password": "1234",
    "name": "테스터",
    "email": "test@naver.com",
    "imageURL": "Image",
    "description": "안녕하세요.",
    "company": "국민대"
}
