### 키워드 정보 접근
GET http://localhost:3000/main/keyword

### 멘토 리스트 정보 접근 
POST http://localhost:3000/main/list
Content-Type: application/json

{
    "keyword": [
        {
            "keywordId": 2,
            "keywordName": "React.js",
            "categoryName": "개발/프로그래밍"
        }
    ],
    "pageNum": 2
}