### 키워드 정보 접근
GET http://localhost:3001/main/keyword

### 멘토 리스트 정보 접근 
POST http://localhost:3001/main/page
Content-Type: application/json

{
    "keyword": [
    {
        "keywordName": "XD", 
        "categoryName": "디자인"   
    },
    {
        "keywordName": "DOM", 
        "categoryName": "디자인"   
    }
        ]
}


### 멘토 리스트 정보 접근 
POST http://localhost:3001/main/list
Content-Type: application/json

{
  "keyword": [
    {   
      "keywordId": 2
    },
    {   
      "keywordId": 1
    },
    {   
      "keywordId": 4
    },
    {   
      "keywordId": 7
    },
    {   
      "keywordId": 9
    },
    {   
      "keywordId": 10
    },
    {   
      "keywordId": 17
    }
  ],
  "pageNum" : 1
}